apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: tsp-app
type: Opaque
stringData:
  SQL_USER: "sqladmin"
  SQL_PASSWORD: "adminutgji89123!@#"  # Replace with actual password
  SQL_DATABASE: "sqldb-tsp"
  SQL_SERVER: "SQL_PRIVATE_IP_HERE"  # Replace with SQL Server private IP